#!/usr/bin/env bash
#
# Usage: ./build-img archlinux-spuma.img disk-layout.sfdisk ~/.ssh/id_rsa.pub
#
# This will create a new bootable Arch Linux system on a virtual disk (qcow2).

# TODO: Add trap to attempt to cleanup unmounting, removing tmp iso filesystem, and disconnecting nbd device when script exits early
set -euo pipefail
set -x

OUT_IMG="$1"
DISK_LAYOUT="$2"
SSH_PUB_KEY_PATH="$3"

QEMU_IMG_BIN="/usr/bin/qemu-img"
QEMU_NBD_BIN="/usr/bin/qemu-nbd"

ISO="/mnt/archmnt"

VDISK_DEVICE="/dev/nbd0"
VDISK_BOOT_DEVICE="${VDISK_DEVICE}p1"
VDISK_SWAP_DEVICE="${VDISK_DEVICE}p2"
VDISK_ROOT_DEVICE="${VDISK_DEVICE}p3"

HOST_SWAP_DEVICE="/dev/nvme0n1p2"

NEW_USER="esimpson"

function err() {
    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
}

function enable_virtual_disks() {
    sudo modprobe nbd max_part=8

    check_nbd $VDISK_DEVICE
}

function create_empty_virtual_disk() {
    $QEMU_IMG_BIN create -f qcow2 $OUT_IMG $1 
}

function check_nbd() {
    # check if we have a block device
    if [ ! -b $1 ]; then
        err "'${1}' is not a block device"
        exit 1
    fi
    # check if block device is not already mounted
    if [[ ! "${1}" =~ ^/dev/nbd[0-9]+$ ]]; then
        err "'${1}' is not a network block device"
        exit 1
    fi

    echo "'${1}' is a valid block device"
}

function check_nbd_partition() {
    # check if we have a block device
    if [ ! -b $1 ]; then
        err "'${1}' is not a block device"
        exit 1
    fi
    # check if block device is not already mounted
    if [[ ! "${1}" =~ ^/dev/nbd[0-9]p[0-9]$ ]]; then
        err "'${1}' is not a network block device partition"
        exit 1
    fi

    echo "'${1}' is a valid block device partition"
}

function mount_virtual_disk() {
    check_nbd $VDISK_DEVICE 

    echo "mounting '${OUT_IMG}' to '${VDISK_DEVICE}'"
    sudo $QEMU_NBD_BIN --connect=$VDISK_DEVICE --format=qcow2 $OUT_IMG
}

function partition_virtual_disk() {
    check_nbd $VDISK_DEVICE

    sudo sfdisk $VDISK_DEVICE < $DISK_LAYOUT
}

function create_filesystems() {
    check_nbd $VDISK_DEVICE
    check_nbd_partition $VDISK_BOOT_DEVICE
    check_nbd_partition $VDISK_SWAP_DEVICE
    check_nbd_partition $VDISK_ROOT_DEVICE

    sudo mkfs.fat -F32 $VDISK_BOOT_DEVICE
    sudo mkswap $VDISK_SWAP_DEVICE
    sudo mkfs.ext4 $VDISK_ROOT_DEVICE
}

function mount_filesystems() {
    check_nbd $VDISK_DEVICE > /dev/null 2>&1
    check_nbd_partition $VDISK_BOOT_DEVICE > /dev/null 2>&1
    check_nbd_partition $VDISK_SWAP_DEVICE > /dev/null 2>&1
    check_nbd_partition $VDISK_ROOT_DEVICE > /dev/null 2>&1

    sudo mkdir -p $ISO 
    sudo mount $VDISK_ROOT_DEVICE $ISO
    sudo mount --mkdir $VDISK_BOOT_DEVICE ${ISO}/boot
    sudo swapon $VDISK_SWAP_DEVICE
}

# Enable nbd disks for system
enable_virtual_disks

# Create the virtual disk to turn into a bootable iso
create_empty_virtual_disk "25G"

# Mount the virtual disk
mount_virtual_disk

# Partition the virtual disk
partition_virtual_disk

# Create filesystems for partitions
create_filesystems

# Mount the filesystems
mount_filesystems 

# Install base packages
sudo pacstrap -K $ISO \
    base \
    linux \
    grub \
    efibootmgr \
    vim \
    openssh \
    python \
    qemu-guest-agent \
    sudo \
    archlinux-keyring

# Generate fstab (handle host swapfile as well)
sudo swapoff $HOST_SWAP_DEVICE
echo "$(genfstab -U ${ISO})" | sudo tee -a "${ISO}/etc/fstab"
sudo swapon $HOST_SWAP_DEVICE

# Run systemd-firstboot
sudo rm "${ISO}/etc/machine-id"
sudo arch-chroot $ISO /usr/bin/systemd-firstboot --locale=C.UTF-8 --timezone=UTC --hostname=archlinux --keymap=us

# Set bootloader settings
sudo arch-chroot $ISO /bin/bash -c "mkdir -p /etc/default"
sudo tee "${ISO}/etc/default/grub" <<EOF
GRUB_TIMEOUT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_DEFAULT=0
EOF

# Setup bootloader (w/ arch-chroot)
sudo arch-chroot $ISO /bin/bash <<EOF
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=archlinux
grub-mkconfig -o /boot/grub/grub.cfg
EOF

# Setup locale
echo "en_US.UTF-8 UTF-8" | sudo tee "${ISO}/etc/locale.gen"
sudo arch-chroot $ISO /usr/bin/locale-gen
echo "LANG=en_US.UTF-8" | sudo tee "${ISO}/etc/locale.conf"
echo "KEYMAP=us" | sudo tee "${ISO}/etc/vconsole.conf"

# Setup users (w/ arch-chroot)
sudo arch-chroot $ISO /usr/bin/useradd -s /bin/bash -m -U $NEW_USER
echo "${NEW_USER} ALL=(ALL) NOPASSWD: ALL" | sudo tee "${ISO}/etc/sudoers.d/${NEW_USER}"

# Setup SSH (w/ arch-chroot)
sudo arch-chroot $ISO /usr/bin/mkdir -m 0700 "/home/${NEW_USER}/.ssh"
sudo arch-chroot $ISO /usr/bin/chown "${NEW_USER}:${NEW_USER}" "/home/${NEW_USER}/.ssh"
sudo cp $SSH_PUB_KEY_PATH "${ISO}/home/${NEW_USER}/.ssh/authorized_keys"
sudo arch-chroot $ISO /usr/bin/chmod 0600 "/home/${NEW_USER}/.ssh/authorized_keys"
sudo arch-chroot $ISO /usr/bin/chown "${NEW_USER}:${NEW_USER}" "/home/${NEW_USER}/.ssh/authorized_keys"
sudo arch-chroot $ISO /usr/bin/sed -i -e '/^#PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
sudo arch-chroot $ISO /usr/bin/sed -i -e '/^#PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
sudo arch-chroot $ISO /usr/bin/sed -i -e '/^#PubkeyAuthentication/s/^.*$/PubkeyAuthentication yes/' /etc/ssh/sshd_config

# Setup Network
sudo tee "${ISO}/etc/systemd/network/10-dhcp.network" <<EOF
[Match]
Name=en*
Name=eth*

[Link]
RequiredForOnline=routable

[Network]
DHCP=yes
EOF

# Populate keyring (w/ arch-chroot)
sudo arch-chroot $ISO /bin/bash <<EOF
pacman-key --init
pacman-key --populate
EOF

# Enable services
services=(sshd systemd-networkd systemd-resolved qemu-guest-agent)
for service in "${services[@]}"; do
    sudo arch-chroot $ISO /usr/bin/systemctl enable $service
done

# Generate initramfs
sudo arch-chroot $ISO /usr/bin/mkinitcpio -P

# Sync any buffered writes & Unmount the filesystems
sync
sudo umount $VDISK_BOOT_DEVICE
sudo swapoff $VDISK_SWAP_DEVICE
sudo umount -l $VDISK_ROOT_DEVICE

# Remove temporary mount
sudo rm -r $ISO

# Unmount the virtual disk
sudo $QEMU_NBD_BIN --disconnect $VDISK_DEVICE
