#!/usr/bin/env bash

set -eux

IMG=$1

sudo qemu-system-x86_64 \
  -m 2048 \
  -enable-kvm \
  -drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd \
  -drive if=pflash,format=raw,file=OVMF_VARS.4m.fd \
  -drive if=virtio,format=qcow2,file=$IMG \
  -netdev tap,id=net0,ifname=tap0,script=no,downscript=no \
  -device virtio-net-pci,netdev=net0 \
  -device virtio-serial \
  -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 \
  -chardev socket,id=qga0,path=/run/qga.sock,server=on,wait=off \
  -vnc :0 \
  -daemonize
